### ISSUE TITLE
Only write to file on formatting change

### ISSUE THREAD

**Issue by NoahTheDuke** [bfontaine/zprint.vim#1]
Hey there! This plugin is great and has been a boon as I've started working on a new large project.

I have a habit of spamming `:w<Enter>` as a tic when I'm thinking or after completing a piece of work. I've noticed that this plugin "changes" the contents of the buffer/file and adds an undo point every time I do, even when the file was already properly formatted.

I'm not great at viml, but it seems like [this](https://github.com/bfontaine/zprint.vim/blob/7eeff04a5ae596d301cae2dd36c4aa882ace982d/autoload/zprint.vim#L25) might be a good place to check if the old buffer and new buffer are different, and only update the file if so?

Thanks so much!

**Comment by NoahTheDuke** [comment]
Here's a solution that works for me:

```vim
  " Write current unsaved buffer to a temp file
  let l:current_lines = zprint#GetLines()
  let l:tmpname1 = tempname() . '.zprint1'
  let l:tmpname2 = tempname() . '.zprint2'
  call writefile(l:current_lines, l:tmpname1)

  let l:cmd = 'zprint < ' . l:tmpname1
  let l:out = zprint#System(l:cmd)
  let l:updated_lines = split(l:out, "\n")

  let diff_offset = len(l:updated_lines) - line('$')

  if l:current_lines != l:updated_lines
    call writefile(l:updated_lines, l:tmpname2)
    call zprint#update_file(l:tmpname2, fname)
  end
```

With this change, the file isn't updated if there's no difference. I bet there's better ways to do this, but I don't know vimscript well enough.

**Comment by bfontaine** [comment]
Hello! Thank you for your feedback and the fixed code; I’m not a VimL master so I [included it as-is](https://github.com/bfontaine/zprint.vim/commit/36cd6733146afd4a8d0cb1e30457d433761d0307).
